version: 0.2

env:
  variables:
    FRONTEND_S3_BUCKET: "deployedapas"
    LAMBDA_FUNCTIONS: "GetNewsFromAPI weatherLambda TriviaQuestionsFunction TellJokeFunction CurrencyExchangeFunction"
    REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Python dependencies for Lambda functions"
      - cd backend
      - cd ../frontend
      - echo "No npm needed, just copying HTML files"

  pre_build:
    commands:
      - echo "Running Pre-Build Commands"
      - pwd
      - ls -al

  build:
    commands:
      - echo "Building backend and syncing frontend"
      - cd ../backend
      - zip -r /tmp/lambda-functions.zip .
      - cd ../frontend
      - aws s3 sync . s3://$FRONTEND_S3_BUCKET/
      - cd ../../

  post_build:
    commands:
      - echo "Deploying Lambda functions directly"
      - |
        for function in $LAMBDA_FUNCTIONS; do
          echo "Deploying $function..."
          aws lambda update-function-code --function-name $function --zip-file fileb:///tmp/lambda-functions.zip --region $REGION
        done
      - echo "Deployment complete!"

artifacts:
  files:
    - lambda-functions.zip
  base-directory: /tmp
  discard-paths: yes
