
version: 0.2

env:
  variables:
    FRONTEND_S3_BUCKET: "deployedapas"  # S3 bucket name for frontend
    LAMBDA_FUNCTIONS: "GetNewsFromAPI weatherLambda TriviaQuestionsFunction TellJokeFunction CurrencyExchangeFunction"  # Space-separated string of Lambda functions
    REGION: "us-east-1"  # AWS region for deployment

phases:
  install:
    runtime-versions:
      python: 3.8  # Modify this to your specific Python runtime version
    commands:
      - echo "Installing Python dependencies for Lambda functions"
      - cd backend
      #- pip install -r requirements.txt -t .  # Install dependencies for Lambda functions
      - cd ../frontend  # Correct path to the frontend directory
      - echo "No npm needed, just copying HTML files"

  pre_build:
    commands:
      - echo "Running Pre-Build Commands"
      - echo "Current directory in pre_build:"
      - pwd
      - echo "Listing files in pre_build:"
      - ls -al
  
  build:
    commands:
      - echo "Building backend (Lambda) and frontend"
      - cd ../backend
      - zip -r /tmp/lambda-functions.zip .  # Create a zip package of the backend Lambda functions
      - cd ../frontend
      - aws s3 sync . s3://$FRONTEND_S3_BUCKET/  # Sync all frontend files (HTML, CSS, JS) to S3
      - cd ../../  # Go back to the root directory
      - cp ./appspec.yml /tmp/  # Ensure appspec.yml is included in the ZIP

  post_build:
    commands:
      - echo "Running Post-Build Commands"
      - echo "Contents of /tmp after build:"
      - ls -al /tmp
      - echo "Deploying Lambda functions"
      - |
        for function in $LAMBDA_FUNCTIONS; do
          aws lambda update-function-code --function-name $function --zip-file fileb:///tmp/lambda-functions.zip --region $REGION
        done
      - echo "Deployment complete!"

artifacts:
  files:
    - lambda-functions.zip  # Lambda function deployment package
    - appspec.yml  # Include appspec.yml file in the artifact
  base-directory: /tmp  # Specify where the artifact is located 
  discard-paths: yes  # Optionally discard paths from the artifact location
